// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./Verifier.sol";

/**
 * ColdChainVerifier — on-chain ZK cold chain registry.
 *
 * Anyone can call submitProof() with a real Groth16 proof.
 * The Groth16Verifier (auto-generated by snarkjs) does the pairing
 * check on-chain; no trusted oracle needed.
 *
 * Public signals layout (matches cold_chain.circom):
 *   pubSignals[0] = minTemp  (scaled *100, +4000 offset)
 *   pubSignals[1] = maxTemp  (scaled *100, +4000 offset)
 *   pubSignals[2] = commitment (Poseidon hash of readings)
 */
contract ColdChainVerifier {
    Groth16Verifier public immutable verifier;

    struct ShipmentRecord {
        bool exists;
        bool isValid;
        uint256 minTemp;   // with offset, as seen by circuit
        uint256 maxTemp;
        uint256 submittedAt;
        string  medicineName;
        address submittedBy;
    }

    // commitment → record
    mapping(uint256 => ShipmentRecord) public shipments;
    uint256[] public commitmentList;

    event ProofSubmitted(
        uint256 indexed commitment,
        bool    isValid,
        uint256 minTemp,
        uint256 maxTemp,
        string  medicineName,
        address submittedBy
    );

    constructor(address _verifier) {
        verifier = Groth16Verifier(_verifier);
    }

    /**
     * Submit a Groth16 proof for on-chain verification.
     * The contract calls Groth16Verifier.verifyProof() — no trust needed.
     *
     * @param _pA          proof.pi_a   (G1 point)
     * @param _pB          proof.pi_b   (G2 point, snarkjs-reversed)
     * @param _pC          proof.pi_c   (G1 point)
     * @param _pubSignals  [minTemp, maxTemp, commitment]
     * @param medicineName human-readable label stored as metadata
     */
    function submitProof(
        uint[2]    calldata _pA,
        uint[2][2] calldata _pB,
        uint[2]    calldata _pC,
        uint[3]    calldata _pubSignals,
        string     calldata medicineName
    ) external returns (bool isValid) {
        isValid = verifier.verifyProof(_pA, _pB, _pC, _pubSignals);

        uint256 commitment = _pubSignals[2];

        if (!shipments[commitment].exists) {
            commitmentList.push(commitment);
        }

        shipments[commitment] = ShipmentRecord({
            exists:       true,
            isValid:      isValid,
            minTemp:      _pubSignals[0],
            maxTemp:      _pubSignals[1],
            submittedAt:  block.timestamp,
            medicineName: medicineName,
            submittedBy:  msg.sender
        });

        emit ProofSubmitted(commitment, isValid, _pubSignals[0], _pubSignals[1], medicineName, msg.sender);
    }

    function isShipmentVerified(uint256 commitment) external view returns (bool) {
        ShipmentRecord storage r = shipments[commitment];
        return r.exists && r.isValid;
    }

    function totalSubmitted() external view returns (uint256) {
        return commitmentList.length;
    }
}
